apiVersion: v1
kind: Template
metadata:
  name: openshift-template
  annotations:
    description: openshift-template
    tags: openshift-template
objects:

- apiVersion: v1
  kind: Service
  metadata:
    name: template-service
  spec:
    ports:
    - port: 8888
      targetPort: 8888
    selector:
      app: openshift-template


- apiVersion: apps/v1
  kind: Deployment
  metadata:
    name: openshift-template
  spec:
    replicas: 1
    revisionHistoryLimit: 3
    selector:
      matchLabels:
        app: openshift-template
    template:
      metadata:
        labels:
          app: openshift-template
      spec:
        containers:
        - image: paas-images.epam.com/proxy/openshift/hello-openshift
          name: openshift-template
          ports:
          - containerPort: 8888
